apiVersion: v1
kind: Namespace
metadata:
  name: devs
  labels:
    environment: dev
    project: prop-development
    owner: developers-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: analytics
  labels:
    environment: analytics
    project: prop-development
    owner: analytics-team
---
